version: '3.3'

services:

  zookeeper:
    build:
      context: zookeeper/
      args:
        ZOOKEEPER_VERSION: $ZOOKEEPER_VERSION
    container_name: zookeeper
    ports:
      - '2181:2181'
    restart: always
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks: 
      - zookeeper_kafka

  kafka:
    build:
      context: kafka/
      args:
        KAFKA_VERSION: $KAFKA_VERSION
    container_name: kafka
    ports:
      - '9092:9092'
    restart: always
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_NUM_PARTITIONS=5
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
    networks: 
      - zookeeper_kafka

networks:
  zookeeper_kafka:
    driver: bridge

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
